// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://pjccfcusphdpbeyofodi.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBqY2NmY3VzcGhkcGJleW9mb2RpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mjk4NTc2MTgsImV4cCI6MjA0NTQzMzYxOH0.7EOAMRXdL8cvi4J9JmKduqRcsMX2cViScNF3bfjaGh8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);